#!/usr/bin/sh

if
	[ $# -eq 1 ]
then
	if
		[ -f $1 ]
	
	then
		read i
		while
			[ $i -ne 0 ]
		do
			echo $i | cat - $1 | ./prog2
			read i
		done
	else
		echo "selmult file"
		exit
	fi
else
	echo "Un paramètre attendu!"
	exit
fi
