build:
	javac -d ./lib ./src/*.java

maj:
	java -cp ./antlr-3.5.jar org.antlr.Tool ./src/projet.g
	javac -d ./lib ./src/*.java

run:
	java projet

mapile:
	java Mapile

edl:
	java Edl

clean:
	rm ./TestsProjet/*.gen ./TestsProjet/*.obj ./TestsProjet/*.desc ./TestsProjet/*.ima ./TestsProjet/*.map
